version: 2
jobs:
  build:
    working_directory: ~/NuffieProductions/ClaimToken
    parallelism: 1
    shell: /bin/bash --login

    docker:
    - image: circleci/ruby:2.6.0-jessie
      environment:
        BUNDLE_PATH: vendor/bundle
    steps:
    - checkout
    - run:
        name: Which bundler?
        command: bundle -v

    - run:
        name: Bundle Install
        command: bundle check || bundle install --jobs=4 --retry=3 --path=$BUNDLE_PATH

    - run:
        name: Running tests...
        command: bundle exec rspec --format documentation
